// <auto-generated />
using System;
using Ats.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ats.Db.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260814033359_AddScreeningCategoryScores")]
    partial class AddScreeningCategoryScores
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Ats.Db.Applications.Application", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CurrentStageId")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRejected")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<Guid>("RequisitionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SubmittedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CurrentStageId");

                    b.HasIndex("RequisitionId");

                    b.HasIndex("CandidateId", "RequisitionId")
                        .IsUnique();

                    b.HasIndex("RequisitionId", "CurrentStageId");

                    b.ToTable("Applications", (string)null);
                });

            modelBuilder.Entity("Ats.Db.Applications.CvAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UploadedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId")
                        .IsUnique();

                    b.ToTable("CvAttachments", (string)null);
                });

            modelBuilder.Entity("Ats.Db.Applications.ScreeningReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Concerns")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("EducationScore")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EvaluatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ExperienceScore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FailureReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("Recommendation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SkillsScore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Strengths")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId")
                        .IsUnique();

                    b.ToTable("ScreeningReports", (string)null);
                });

            modelBuilder.Entity("Ats.Db.Pipeline.StageTransition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorDisplayLabel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorKind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("FromStageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FromStageName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ToStageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ToStageName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("FromStageId");

                    b.HasIndex("ToStageId");

                    b.HasIndex("ApplicationId", "OccurredAtUtc");

                    b.ToTable("StageTransitions", (string)null);
                });

            modelBuilder.Entity("Ats.Db.Requisitions.Requisition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Draft");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("Requisitions", (string)null);
                });

            modelBuilder.Entity("Ats.Db.Requisitions.Stage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RequisitionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("RequisitionId");

                    b.HasIndex("RequisitionId", "NormalizedName")
                        .IsUnique();

                    b.ToTable("Stages", (string)null);
                });

            modelBuilder.Entity("Ats.Shared.Auth.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d6b4122d-6228-4e08-bf29-43c3d5e23a01"),
                            ConcurrencyStamp = "d6b4122d-6228-4e08-bf29-43c3d5e23a01",
                            Name = "Candidate",
                            NormalizedName = "CANDIDATE"
                        },
                        new
                        {
                            Id = new Guid("d6b4122d-6228-4e08-bf29-43c3d5e23a02"),
                            ConcurrencyStamp = "d6b4122d-6228-4e08-bf29-43c3d5e23a02",
                            Name = "Recruiter",
                            NormalizedName = "RECRUITER"
                        },
                        new
                        {
                            Id = new Guid("d6b4122d-6228-4e08-bf29-43c3d5e23a03"),
                            ConcurrencyStamp = "d6b4122d-6228-4e08-bf29-43c3d5e23a03",
                            Name = "HiringManager",
                            NormalizedName = "HIRINGMANAGER"
                        });
                });

            modelBuilder.Entity("Ats.Shared.Auth.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d6b4122d-6228-4e08-bf29-43c3d5e23b01"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d6b4122d-6228-4e08-bf29-43c3d5e23b01",
                            CreatedAtUtc = new DateTime(2026, 8, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "sample.candidate@d4fape-ats.local",
                            EmailConfirmed = false,
                            FirstName = "Sample",
                            LastName = "Candidate",
                            LockoutEnabled = true,
                            NormalizedEmail = "SAMPLE.CANDIDATE@D4FAPE-ATS.LOCAL",
                            NormalizedUserName = "SAMPLE.CANDIDATE@D4FAPE-ATS.LOCAL",
                            PasswordHash = "AQAAAAIAAYagAAAAEOtx0o7XBEX91ZfQpzpRzQRdjjNKgXHPuOpNiKax7WTqd/M0OzWUpco0hClbyO1bJQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d6b4122d-6228-4e08-bf29-43c3d5e23c01",
                            TwoFactorEnabled = false,
                            UserName = "sample.candidate@d4fape-ats.local"
                        },
                        new
                        {
                            Id = new Guid("d6b4122d-6228-4e08-bf29-43c3d5e23b02"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d6b4122d-6228-4e08-bf29-43c3d5e23b02",
                            CreatedAtUtc = new DateTime(2026, 8, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "sample.recruiter@d4fape-ats.local",
                            EmailConfirmed = false,
                            FirstName = "Sample",
                            LastName = "Recruiter",
                            LockoutEnabled = true,
                            NormalizedEmail = "SAMPLE.RECRUITER@D4FAPE-ATS.LOCAL",
                            NormalizedUserName = "SAMPLE.RECRUITER@D4FAPE-ATS.LOCAL",
                            PasswordHash = "AQAAAAIAAYagAAAAEOtx0o7XBEX91ZfQpzpRzQRdjjNKgXHPuOpNiKax7WTqd/M0OzWUpco0hClbyO1bJQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d6b4122d-6228-4e08-bf29-43c3d5e23c02",
                            TwoFactorEnabled = false,
                            UserName = "sample.recruiter@d4fape-ats.local"
                        },
                        new
                        {
                            Id = new Guid("d6b4122d-6228-4e08-bf29-43c3d5e23b03"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d6b4122d-6228-4e08-bf29-43c3d5e23b03",
                            CreatedAtUtc = new DateTime(2026, 8, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "sample.hiringmanager@d4fape-ats.local",
                            EmailConfirmed = false,
                            FirstName = "Sample",
                            LastName = "Hiring Manager",
                            LockoutEnabled = true,
                            NormalizedEmail = "SAMPLE.HIRINGMANAGER@D4FAPE-ATS.LOCAL",
                            NormalizedUserName = "SAMPLE.HIRINGMANAGER@D4FAPE-ATS.LOCAL",
                            PasswordHash = "AQAAAAIAAYagAAAAEOtx0o7XBEX91ZfQpzpRzQRdjjNKgXHPuOpNiKax7WTqd/M0OzWUpco0hClbyO1bJQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d6b4122d-6228-4e08-bf29-43c3d5e23c03",
                            TwoFactorEnabled = false,
                            UserName = "sample.hiringmanager@d4fape-ats.local"
                        });
                });

            modelBuilder.Entity("Ats.Shared.Auth.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("d6b4122d-6228-4e08-bf29-43c3d5e23b01"),
                            RoleId = new Guid("d6b4122d-6228-4e08-bf29-43c3d5e23a01")
                        },
                        new
                        {
                            UserId = new Guid("d6b4122d-6228-4e08-bf29-43c3d5e23b02"),
                            RoleId = new Guid("d6b4122d-6228-4e08-bf29-43c3d5e23a02")
                        },
                        new
                        {
                            UserId = new Guid("d6b4122d-6228-4e08-bf29-43c3d5e23b03"),
                            RoleId = new Guid("d6b4122d-6228-4e08-bf29-43c3d5e23a03")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Ats.Db.Applications.Application", b =>
                {
                    b.HasOne("Ats.Shared.Auth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ats.Db.Requisitions.Stage", null)
                        .WithMany()
                        .HasForeignKey("CurrentStageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ats.Db.Requisitions.Requisition", null)
                        .WithMany()
                        .HasForeignKey("RequisitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ats.Db.Applications.CvAttachment", b =>
                {
                    b.HasOne("Ats.Db.Applications.Application", null)
                        .WithOne("CvAttachment")
                        .HasForeignKey("Ats.Db.Applications.CvAttachment", "ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ats.Db.Applications.ScreeningReport", b =>
                {
                    b.HasOne("Ats.Db.Applications.Application", null)
                        .WithOne("ScreeningReport")
                        .HasForeignKey("Ats.Db.Applications.ScreeningReport", "ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ats.Db.Pipeline.StageTransition", b =>
                {
                    b.HasOne("Ats.Shared.Auth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Ats.Db.Applications.Application", null)
                        .WithMany()
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ats.Db.Requisitions.Stage", null)
                        .WithMany()
                        .HasForeignKey("FromStageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Ats.Db.Requisitions.Stage", null)
                        .WithMany()
                        .HasForeignKey("ToStageId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Ats.Db.Requisitions.Stage", b =>
                {
                    b.HasOne("Ats.Db.Requisitions.Requisition", null)
                        .WithMany("Stages")
                        .HasForeignKey("RequisitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ats.Shared.Auth.RefreshToken", b =>
                {
                    b.HasOne("Ats.Shared.Auth.ApplicationUser", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Ats.Shared.Auth.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Ats.Shared.Auth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Ats.Shared.Auth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Ats.Shared.Auth.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ats.Shared.Auth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Ats.Shared.Auth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ats.Db.Applications.Application", b =>
                {
                    b.Navigation("CvAttachment");

                    b.Navigation("ScreeningReport");
                });

            modelBuilder.Entity("Ats.Db.Requisitions.Requisition", b =>
                {
                    b.Navigation("Stages");
                });

            modelBuilder.Entity("Ats.Shared.Auth.ApplicationUser", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
