<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Ats.ArchitectureTests</RootNamespace>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.13.0" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.0.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Db\Ats.Db.csproj" />
    <ProjectReference Include="..\..\src\Service\Ats.Service.csproj" />
    <ProjectReference Include="..\..\src\Api\Ats.Api.csproj" />
    <ProjectReference Include="..\..\src\Shared\Ats.Shared.csproj" />
  </ItemGroup>

</Project>
